services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - ./src:/app/src
      - node_modules:/app/node_modules
      - build:/app/.next
    environment:
      - NODE_ENV=production
    networks:
      - prod-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  node_modules:
  build:

networks:
  prod-network:
